site_name: PyGUIAdapter Docs
repo_url: https://github.com/zimolab/PyGUIAdapter
docs_dir: ./docs/

theme:
  name: material
  language: zh

nav:
  - 首页: index.md
  - 快速开始: quickstart.md
  - 添加多个函数: multiple-functions.md
  - 配置控件属性: widget-config.md
  - 参数与控件:
      - 控件类型映射表: widget-map.md
      - 基础类型与控件: basic-types.md
      - 扩展类型与控件: extend-types.md
  - 配置窗口属性: window.md
  - 窗口工具栏: toolbar.md
  - 窗口菜单栏: menu.md
  - 取消函数执行: cancel.md
  - 进度条: progressbar.md
  - 与用户交互: user-interaction.md
  - 界面美化: style.md
  - 自定义控件: custom-widget.md
  - 实用函数: utility.md
  - 关于图标: icon_type.md
  - 应用打包: packaging.md
  - API参考:
    - pyguiadapter.window: apis/pyguiadapter.window.md
    - pyguiadapter.action: apis/pyguiadapter.action.md
    - pyguiadapter.toolbar: apis/pyguiadapter.toolbar.md
    - pyguiadapter.menu: apis/pyguiadapter.menu.md
    - pyguiadapter.toast: apis/pyguiadapter.toast.md
    - pyguiadapter.adapter.adapter: apis/pyguiadapter.adapter.adapter.md
    - pyguiadapter.adapter.ucontext: apis/pyguiadapter.adapter.ucontext.md
    - pyguiadapter.adapter.uoutput: apis/pyguiadapter.adapter.uoutput.md
    - pyguiadapter.adapter.uinput: apis/pyguiadapter.adapter.uinput.md
    - pyguiadapter.adapter.uprogress: apis/pyguiadapter.adapter.uprogress.md
    - pyguiadapter.adapter.udialog: apis/pyguiadapter.adapter.udialog.md
    - pyguiadapter.adapter.ubeep: apis/pyguiadapter.adapter.ubeep.md
    - pyguiadapter.adapter.utoast: apis/pyguiadapter.adapter.utoast.md
    - pyguiadapter.adapter.uclipboard: apis/pyguiadapter.adapter.uclipboard.md
    - pyguiadapter.textbrowser: apis/pyguiadapter.textbrowser.md
    - pyguiadapter.windows: apis/pyguiadapter.windows.md
    - pyguiadapter.windows.fnexec: apis/pyguiadapter.windows.fnexec.md
    - pyguiadapter.windows.fnselect: apis/pyguiadapter.windows.fnselect.md
    - pyguiadapter.paramwidget: apis/pyguiadapter.paramwidget.md
    - pyguiadapter.widgets.common: apis/pyguiadapter.widgets.common.md
    - pyguiadapter.widgets.intspin: apis/pyguiadapter.widgets.intspin.md
    - pyguiadapter.widgets.floatspin: apis/pyguiadapter.widgets.floatspin.md
    - pyguiadapter.widgets.boolbox: apis/pyguiadapter.widgets.boolbox.md
    - pyguiadapter.widgets.listedit: apis/pyguiadapter.widgets.listedit.md
    - pyguiadapter.widgets.tupleedit: apis/pyguiadapter.widgets.tupleedit.md
    - pyguiadapter.widgets.dictedit: apis/pyguiadapter.widgets.dictedit.md
    - pyguiadapter.widgets.setedit: apis/pyguiadapter.widgets.setedit.md
    - pyguiadapter.widgets.enumselect: apis/pyguiadapter.widgets.enumselect.md
    - pyguiadapter.widgets.lineedit: apis/pyguiadapter.widgets.lineedit.md
    - pyguiadapter.widgets.exclusivechoice: apis/pyguiadapter.widgets.exclusivechoice.md
    - pyguiadapter.widgets.datetimeedit: apis/pyguiadapter.widgets.datetimeedit.md
    - pyguiadapter.widgets.dateedit: apis/pyguiadapter.widgets.dateedit.md
    - pyguiadapter.widgets.timeedit: apis/pyguiadapter.widgets.timeedit.md
    - pyguiadapter.widgets.pyliteraledit: apis/pyguiadapter.widgets.pyliteraledit.md
    - pyguiadapter.widgets.intedit: apis/pyguiadapter.widgets.intedit.md
    - pyguiadapter.widgets.floatedit: apis/pyguiadapter.widgets.floatedit.md
    - pyguiadapter.widgets.choicebox: apis/pyguiadapter.widgets.choicebox.md
    - pyguiadapter.widgets.colorpicker: apis/pyguiadapter.widgets.colorpicker.md
    - pyguiadapter.widgets.dial: apis/pyguiadapter.widgets.dial.md
    - pyguiadapter.widgets.slider: apis/pyguiadapter.widgets.slider.md
    - pyguiadapter.widgets.dirselect: apis/pyguiadapter.widgets.dirselect.md
    - pyguiadapter.widgets.fileselect: apis/pyguiadapter.widgets.fileselect.md
    - pyguiadapter.widgets.jsonedit: apis/pyguiadapter.widgets.jsonedit.md
    - pyguiadapter.widgets.keysequenceedit: apis/pyguiadapter.widgets.keysequenceedit.md
    - pyguiadapter.widgets.multichoice: apis/pyguiadapter.widgets.multichoice.md
    - pyguiadapter.widgets.plaindict: apis/pyguiadapter.widgets.plaindict.md
    - pyguiadapter.widgets.stringlist: apis/pyguiadapter.widgets.stringlist.md
    - pyguiadapter.widgets.textedit: apis/pyguiadapter.widgets.textedit.md
  - 贡献: contribution.md
  - 开源许可: license.md
  - 版本历史: changelog.md

plugins:
  - search:

  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false
            separate_signature: false
            show_signature_annotations: true
            signature_crossrefs: true
            modernize_annotations: true
          selection:
            docstring_style: google
            filters: "! (^_|^__)"  # 过滤掉私有方法和属性
  - i18n:
      docs_structure: folder
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          default: false
          name: English
          build: true

  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true

  - macros:

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


extra:
  repo_url: https://github.com/zimolab/PyGUIAdapter
  main_branch: https://github.com/zimolab/PyGUIAdapter/tree/main