[tool.poetry]
name = "pyguiadapter"
version = "0.1.3"
description = "turn (almost) any python functions into a gui in a few lines of code"
authors = ["zimolab <zimolab@aliyun.com>"]
readme = "README.md"

[tool.poetry.scripts]
autogen = "autouic:main"

[tool.poetry.dependencies]
python = "^3.10, <3.11"
function2widgets = "^0.3.0"

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

