[tool.poetry]
name = "pyguiadapter"
version = "0.1.0"
description = "turn (almost) any python functions into a gui in a few lines of code"
authors = ["zimolab <zimolab@aliyun.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10, <3.11"
function2widgets = "^0.2.0"
pyqt6 = "^6.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
