[tool.poetry]
name = "pyguiadapter"
version = "0.1.6"
description = "turn (almost) any python functions into a gui in a few lines of code"
authors = ["zimolab <zimolab@aliyun.com>"]
readme = "README.md"
homepage = "https://github.com/zimolab/PyGUIAdapter"
repository = "https://github.com/zimolab/PyGUIAdapter"
documentation = "https://github.com/zimolab/PyGUIAdapter"


[tool.poetry.scripts]
autogen = "autouic:main"

[tool.poetry.dependencies]
python = "^3.10, <3.11"
function2widgets = "^0.3.0"

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"
qt-material = "^2.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

