CLIPBOARD_SET_TEXT = 0
CLIPBOARD_GET_TEXT = 1
CLIPBOARD_SUPPORTS_SELECTION = 2
CLIPBOARD_GET_SELECTION_TEXT = 3
CLIPBOARD_SET_SELECTION_TEXT = 4
CLIPBOARD_OWNS_SELECTION = 5
CLIPBOARD_OWNS_CLIPBOARD = 6
